### ISSUE TITLE
Form Issue

### ISSUE THREAD

**Issue by PSY27** [PSY27/web-dev#1]
Fix the submit button on contact page

**Comment by masteradit** [comment]
Hey! I think I can fix this issue. Can you assign it to me?

**Comment by PSY27** [comment]
Yes please

**Comment by trolzen** [comment]
Hi, @PSY27 ! What do you mean by "fixing the submit button"?
If the desired functionality is to save the form data somewhere, then I guess it's not an easy task in these circumstances. For this to work you need some server-side functionality (which will do the actual work), but I doubt that Netlify has this functionality.

**Comment by PSY27** [comment]
yeah i know that adit offered to do that for me

**Comment by masteradit** [comment]
> I doubt that Netlify has this functionality

Hey @trolzen! Netlify has a feature for forms. I have worked with it in the past, so that's why I thought of fixing this issue. Honestly, it is pretty easy too. I'll push the code in a few minutes 😄

**Comment by trolzen** [comment]
> > I doubt that Netlify has this functionality
> 
> Hey @trolzen! Netlify has a feature for forms. I have worked with it in the past, so that's why I thought of fixing this issue. Honestly, it is pretty easy too. I'll push the code in a few minutes smile

OK, looking forward to see your code, since I'm curious how it will work. :+1:
