### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by PSY27** [PSY27/web-dev#2]
in detail Documentaion required

**Comment by onosyoono** [comment]
I would like to try this out!

**Comment by PSY27** [comment]
do you think you can improve this?

**Comment by onosyoono** [comment]
Yup, I have explored Web Development and I think I can improve documentation and make it more ordered.

**Comment by PSY27** [comment]
alright go ahead

**Comment by onosyoono** [comment]
I have included page-wise details regarding the website. I'll be making a pull request for validation.
